from app.services.contracts import AgentResult,Finding
def mock_result(name,case):
 common=dict(status='partial',confidence=.55,warnings=['mock_fallback'],sources=[],metadata={'analysis_source':'mock'})
 if name=='evidence':
  hits=case.evidence_context
  facts=[h.get('text','') for h in hits[:5]] or [case.description]
  sources=[{'source_id':h.get('source_id'),'title':h.get('title'),'source_ref':h.get('source_ref'),'trust_level':h.get('trust_level')} for h in hits]
  missing=[] if hits else ['المالك المسؤول','النتيجة المطلوبة','الأدلة الداعمة']
  return AgentResult(name,headline='تم ربط الأدلة' if hits else 'المعلومات تحتاج استكمال',summary='تم استخدام أدلة Knowledge Fabric.' if hits else 'تم استلام وصف القضية لكن الأدلة المستقلة غير متاحة بعد.',findings=[Finding('دليل مسترجع' if hits else 'وصف القضية',f,verified=bool(hits)) for f in facts],data={'facts':facts,'claims':[],'assumptions':[],'missing_information':missing,'required_evidence':[] if hits else ['آخر تقرير حالة'],'readiness':'high' if hits else 'low'},sources=sources,**{k:v for k,v in common.items() if k!='sources'})
 if name=='risk':return AgentResult(name,headline='مخاطر غير مكتملة',summary='يمكن تحديد المخاطر بدقة أكبر بعد استكمال الأدلة.',data={'risk_level':'medium','top_risks':['قرار بمعلومات ناقصة'],'mitigations':['استكمال المعلومات']},**common)
 if name=='options':return AgentResult(name,headline='ثلاثة بدائل',summary='تم بناء ثلاثة مسارات أولية.',data={'options':[{'id':'A','title':'الاستمرار بضوابط','description':'الاستمرار مع بوابات تحقق.','benefits':['الاستمرارية'],'risks':['نقص الأدلة'],'conditions':['تحديد المالك'],'criterion_scores':{'compliance':65,'risk':55,'financial':70,'time':80,'strategy':70,'stakeholder':65}},{'id':'B','title':'مراجعة قصيرة قبل الالتزام','description':'استكمال الأدلة الحرجة ثم القرار.','benefits':['جودة قرار أعلى'],'risks':['تأخير محدود'],'conditions':['جمع الأدلة'],'criterion_scores':{'compliance':85,'risk':80,'financial':60,'time':55,'strategy':80,'stakeholder':75}},{'id':'C','title':'إعادة تصميم المسار','description':'إعادة تصميم النطاق المتأثر.','benefits':['حل جذري'],'risks':['وقت وتكلفة'],'conditions':['تأكيد الحاجة'],'criterion_scores':{'compliance':90,'risk':85,'financial':45,'time':35,'strategy':90,'stakeholder':60}}]},**common)
 if name=='critic':return AgentResult(name,status='partial',headline='مراجعة مستقلة',summary='الترتيب يعتمد على جودة الأدلة.',data={'challenges':['هل الأدلة كافية؟'],'hidden_assumptions':[],'reversal_conditions':['دليل جوهري جديد']},confidence=.75,warnings=[],sources=[],metadata={'analysis_source':'mock'})
 if name=='chief_advisor':return AgentResult(name,headline='استكمال الأدلة أولًا',summary='الأفضل استكمال المعلومات الحرجة قبل الالتزام النهائي.',data={'decision_label':'استكمال المعلومات قبل القرار','recommended_option_id':'B','why':['المعلومات غير مكتملة'],'next_actions':['تحديد المالك','جمع آخر تقرير حالة','تحديد موعد قرار'],'top_risks':['التأخير','قرار بمعلومات ناقصة'],'decision_conditions':['توفر الأدلة الأساسية'],'confidence':.55,'human_decision_required':True},**common)
 return AgentResult(name,headline='تحليل احتياطي',summary='تم استخدام المسار الاحتياطي لهذه الجزئية.',data={},**common)
