'use client';
import {FormEvent,useState} from 'react';
import {useRouter} from 'next/navigation';
import {useLang} from '@/components/LanguageProvider';
export default function Login(){
 const r=useRouter(),{t}=useLang();const[busy,setBusy]=useState(false),[err,setErr]=useState('');
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setErr('');const f=new FormData(e.currentTarget);const key=String(f.get('key')||'');const res=await fetch('/api/session/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({key})});if(!res.ok){setErr(t('بيانات الدخول غير صحيحة','Invalid credentials'));setBusy(false);return;}r.push('/');r.refresh();}
 return <main className="authPage"><section className="authAside"><span className="pill">{t('دخول آمن','Secure access')}</span><h1>{t('أهلًا بعودتك. قراراتك بانتظارك.','Welcome back. Your decisions are waiting.')}</h1><p>{t('ادخل إلى مساحة مؤسستك وتابع المشاريع والحالات بحسب صلاحيتك.','Enter your organization workspace and continue with the projects and cases available to your role.')}</p><div className="authQuote">{t('كل قرار موثّق. كل توصية لها مصدر. والاعتماد دائمًا بيدك.','Every decision is documented, every recommendation has a source, and approval always stays with you.')}</div></section><section className="authCard"><span className="kicker">{t('تسجيل الدخول','Sign in')}</span><h2>{t('ادخل إلى حسابك','Access your account')}</h2><p className="muted">{t('تستخدم النسخة الحالية رمز الدخول المؤسسي. سيتحول لاحقًا إلى البريد وكلمة المرور عند ربط مزوّد الهوية.','This release uses your organization access code. Email and password will replace it when the identity provider is connected.')}</p><form onSubmit={submit}><div className="field"><label>{t('رمز الدخول المؤسسي','Organization access code')}</label><input name="key" type="password" autoComplete="current-password" placeholder="••••••••••••" required/><small>{t('تحصل عليه من مسؤول النظام في مؤسستك.','Provided by your organization administrator.')}</small></div>{err&&<div className="errorBox">{err}</div>}<button className="btn primary full" disabled={busy}>{busy?t('جارٍ التحقق...','Signing in...'):t('دخول إلى المساحة','Enter workspace')}</button></form><p className="formFoot">{t('ليس لديك حساب؟','Don’t have an account?')} <a href="/signup">{t('اطلب تفعيل حساب','Request access')}</a></p></section></main>
}
