"""v6 initial schema

Revision ID: 21cbfdcab740
Revises: 
Create Date: 2026-08-08 00:17:54.825691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21cbfdcab740'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events_v6',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=80), nullable=False),
    sa.Column('actor', sa.String(length=200), nullable=False),
    sa.Column('auth_type', sa.String(length=30), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('resource_type', sa.String(length=60), nullable=True),
    sa.Column('resource_id', sa.String(length=80), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_v6_actor'), 'audit_events_v6', ['actor'], unique=False)
    op.create_index(op.f('ix_audit_events_v6_created_at'), 'audit_events_v6', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_v6_event_type'), 'audit_events_v6', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_events_v6_request_id'), 'audit_events_v6', ['request_id'], unique=False)
    op.create_index(op.f('ix_audit_events_v6_resource_id'), 'audit_events_v6', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_events_v6_resource_type'), 'audit_events_v6', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_events_v6_tenant_id'), 'audit_events_v6', ['tenant_id'], unique=False)
    op.create_table('automation_runs_v5',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=80), nullable=False),
    sa.Column('actor', sa.String(length=200), nullable=True),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('workflow_id', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('approved', sa.Integer(), nullable=False),
    sa.Column('dry_run', sa.Integer(), nullable=False),
    sa.Column('input_json', sa.Text(), nullable=True),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automation_runs_v5_actor'), 'automation_runs_v5', ['actor'], unique=False)
    op.create_index(op.f('ix_automation_runs_v5_case_id'), 'automation_runs_v5', ['case_id'], unique=False)
    op.create_index(op.f('ix_automation_runs_v5_tenant_id'), 'automation_runs_v5', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_automation_runs_v5_workflow_id'), 'automation_runs_v5', ['workflow_id'], unique=False)
    op.create_table('cost_budgets_v6',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=80), nullable=False),
    sa.Column('daily_budget_usd', sa.Float(), nullable=False),
    sa.Column('case_run_budget_usd', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_budgets_v6_tenant_id'), 'cost_budgets_v6', ['tenant_id'], unique=True)
    op.create_table('decision_approvals_v51',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=80), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('option_id', sa.String(length=40), nullable=False),
    sa.Column('decision_owner', sa.String(length=200), nullable=False),
    sa.Column('approved_by', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_approvals_v51_approved_by'), 'decision_approvals_v51', ['approved_by'], unique=False)
    op.create_index(op.f('ix_decision_approvals_v51_case_id'), 'decision_approvals_v51', ['case_id'], unique=False)
    op.create_index(op.f('ix_decision_approvals_v51_status'), 'decision_approvals_v51', ['status'], unique=False)
    op.create_index(op.f('ix_decision_approvals_v51_tenant_id'), 'decision_approvals_v51', ['tenant_id'], unique=False)
    op.create_table('decision_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=80), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('urgency', sa.String(length=30), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('selected_agents', sa.JSON(), nullable=True),
    sa.Column('skipped_agents', sa.JSON(), nullable=True),
    sa.Column('agent_results', sa.JSON(), nullable=True),
    sa.Column('analysis', sa.JSON(), nullable=True),
    sa.Column('audit_log', sa.JSON(), nullable=True),
    sa.Column('analysis_source', sa.String(length=30), nullable=True),
    sa.Column('approved_option', sa.String(length=20), nullable=True),
    sa.Column('decision_owner', sa.String(length=200), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_cases_created_by'), 'decision_cases', ['created_by'], unique=False)
    op.create_index(op.f('ix_decision_cases_tenant_id'), 'decision_cases', ['tenant_id'], unique=False)
    op.create_table('knowledge_chunks_v5',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=80), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding_json', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_chunks_v5_case_id'), 'knowledge_chunks_v5', ['case_id'], unique=False)
    op.create_index(op.f('ix_knowledge_chunks_v5_source_id'), 'knowledge_chunks_v5', ['source_id'], unique=False)
    op.create_index(op.f('ix_knowledge_chunks_v5_tenant_id'), 'knowledge_chunks_v5', ['tenant_id'], unique=False)
    op.create_table('knowledge_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=80), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('source_ref', sa.String(length=1000), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_items_case_id'), 'knowledge_items', ['case_id'], unique=False)
    op.create_index(op.f('ix_knowledge_items_source_type'), 'knowledge_items', ['source_type'], unique=False)
    op.create_index(op.f('ix_knowledge_items_tenant_id'), 'knowledge_items', ['tenant_id'], unique=False)
    op.create_table('knowledge_sources_v5',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=80), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('source_ref', sa.String(length=1500), nullable=True),
    sa.Column('object_key', sa.String(length=1500), nullable=True),
    sa.Column('trust_level', sa.String(length=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_sources_v5_case_id'), 'knowledge_sources_v5', ['case_id'], unique=False)
    op.create_index(op.f('ix_knowledge_sources_v5_source_type'), 'knowledge_sources_v5', ['source_type'], unique=False)
    op.create_index(op.f('ix_knowledge_sources_v5_status'), 'knowledge_sources_v5', ['status'], unique=False)
    op.create_index(op.f('ix_knowledge_sources_v5_tenant_id'), 'knowledge_sources_v5', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_knowledge_sources_v5_trust_level'), 'knowledge_sources_v5', ['trust_level'], unique=False)
    op.create_table('mcp_server_registrations_v6',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=80), nullable=False),
    sa.Column('server_key', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('auth_type', sa.String(length=20), nullable=False),
    sa.Column('auth_env_var', sa.String(length=120), nullable=True),
    sa.Column('tool_allowlist_json', sa.Text(), nullable=True),
    sa.Column('timeout_seconds', sa.Float(), nullable=False),
    sa.Column('last_health_status', sa.String(length=20), nullable=True),
    sa.Column('last_health_at', sa.DateTime(), nullable=True),
    sa.Column('last_health_detail', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mcp_server_registrations_v6_server_key'), 'mcp_server_registrations_v6', ['server_key'], unique=False)
    op.create_index(op.f('ix_mcp_server_registrations_v6_tenant_id'), 'mcp_server_registrations_v6', ['tenant_id'], unique=False)
    op.create_table('scan_results_v6',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=80), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('engine', sa.String(length=60), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('scanned_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_results_v6_source_id'), 'scan_results_v6', ['source_id'], unique=False)
    op.create_index(op.f('ix_scan_results_v6_status'), 'scan_results_v6', ['status'], unique=False)
    op.create_index(op.f('ix_scan_results_v6_tenant_id'), 'scan_results_v6', ['tenant_id'], unique=False)
    op.create_table('usage_records_v6',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=80), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('agent', sa.String(length=80), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('cost_basis', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_records_v6_agent'), 'usage_records_v6', ['agent'], unique=False)
    op.create_index(op.f('ix_usage_records_v6_case_id'), 'usage_records_v6', ['case_id'], unique=False)
    op.create_index(op.f('ix_usage_records_v6_created_at'), 'usage_records_v6', ['created_at'], unique=False)
    op.create_index(op.f('ix_usage_records_v6_request_id'), 'usage_records_v6', ['request_id'], unique=False)
    op.create_index(op.f('ix_usage_records_v6_tenant_id'), 'usage_records_v6', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_records_v6_tenant_id'), table_name='usage_records_v6')
    op.drop_index(op.f('ix_usage_records_v6_request_id'), table_name='usage_records_v6')
    op.drop_index(op.f('ix_usage_records_v6_created_at'), table_name='usage_records_v6')
    op.drop_index(op.f('ix_usage_records_v6_case_id'), table_name='usage_records_v6')
    op.drop_index(op.f('ix_usage_records_v6_agent'), table_name='usage_records_v6')
    op.drop_table('usage_records_v6')
    op.drop_index(op.f('ix_scan_results_v6_tenant_id'), table_name='scan_results_v6')
    op.drop_index(op.f('ix_scan_results_v6_status'), table_name='scan_results_v6')
    op.drop_index(op.f('ix_scan_results_v6_source_id'), table_name='scan_results_v6')
    op.drop_table('scan_results_v6')
    op.drop_index(op.f('ix_mcp_server_registrations_v6_tenant_id'), table_name='mcp_server_registrations_v6')
    op.drop_index(op.f('ix_mcp_server_registrations_v6_server_key'), table_name='mcp_server_registrations_v6')
    op.drop_table('mcp_server_registrations_v6')
    op.drop_index(op.f('ix_knowledge_sources_v5_trust_level'), table_name='knowledge_sources_v5')
    op.drop_index(op.f('ix_knowledge_sources_v5_tenant_id'), table_name='knowledge_sources_v5')
    op.drop_index(op.f('ix_knowledge_sources_v5_status'), table_name='knowledge_sources_v5')
    op.drop_index(op.f('ix_knowledge_sources_v5_source_type'), table_name='knowledge_sources_v5')
    op.drop_index(op.f('ix_knowledge_sources_v5_case_id'), table_name='knowledge_sources_v5')
    op.drop_table('knowledge_sources_v5')
    op.drop_index(op.f('ix_knowledge_items_tenant_id'), table_name='knowledge_items')
    op.drop_index(op.f('ix_knowledge_items_source_type'), table_name='knowledge_items')
    op.drop_index(op.f('ix_knowledge_items_case_id'), table_name='knowledge_items')
    op.drop_table('knowledge_items')
    op.drop_index(op.f('ix_knowledge_chunks_v5_tenant_id'), table_name='knowledge_chunks_v5')
    op.drop_index(op.f('ix_knowledge_chunks_v5_source_id'), table_name='knowledge_chunks_v5')
    op.drop_index(op.f('ix_knowledge_chunks_v5_case_id'), table_name='knowledge_chunks_v5')
    op.drop_table('knowledge_chunks_v5')
    op.drop_index(op.f('ix_decision_cases_tenant_id'), table_name='decision_cases')
    op.drop_index(op.f('ix_decision_cases_created_by'), table_name='decision_cases')
    op.drop_table('decision_cases')
    op.drop_index(op.f('ix_decision_approvals_v51_tenant_id'), table_name='decision_approvals_v51')
    op.drop_index(op.f('ix_decision_approvals_v51_status'), table_name='decision_approvals_v51')
    op.drop_index(op.f('ix_decision_approvals_v51_case_id'), table_name='decision_approvals_v51')
    op.drop_index(op.f('ix_decision_approvals_v51_approved_by'), table_name='decision_approvals_v51')
    op.drop_table('decision_approvals_v51')
    op.drop_index(op.f('ix_cost_budgets_v6_tenant_id'), table_name='cost_budgets_v6')
    op.drop_table('cost_budgets_v6')
    op.drop_index(op.f('ix_automation_runs_v5_workflow_id'), table_name='automation_runs_v5')
    op.drop_index(op.f('ix_automation_runs_v5_tenant_id'), table_name='automation_runs_v5')
    op.drop_index(op.f('ix_automation_runs_v5_case_id'), table_name='automation_runs_v5')
    op.drop_index(op.f('ix_automation_runs_v5_actor'), table_name='automation_runs_v5')
    op.drop_table('automation_runs_v5')
    op.drop_index(op.f('ix_audit_events_v6_tenant_id'), table_name='audit_events_v6')
    op.drop_index(op.f('ix_audit_events_v6_resource_type'), table_name='audit_events_v6')
    op.drop_index(op.f('ix_audit_events_v6_resource_id'), table_name='audit_events_v6')
    op.drop_index(op.f('ix_audit_events_v6_request_id'), table_name='audit_events_v6')
    op.drop_index(op.f('ix_audit_events_v6_event_type'), table_name='audit_events_v6')
    op.drop_index(op.f('ix_audit_events_v6_created_at'), table_name='audit_events_v6')
    op.drop_index(op.f('ix_audit_events_v6_actor'), table_name='audit_events_v6')
    op.drop_table('audit_events_v6')
    # ### end Alembic commands ###
